### ISSUE TITLE
"Windows Protected Your PC"

### ISSUE THREAD

**Issue by MineDash123** [GDColon/MC2GD#2]
Got this pop-up when I tried to run MC2GD.bat, what do I do? (I **can** run it by clicking "More info" then I can run it)
![protecc](https://user-images.githubusercontent.com/63759839/79402443-6f068c00-7f51-11ea-856c-276153b0310f.png)

**Comment by GDColon** [comment]
It's just Windows being dumb

**Comment by vinnieleverton** [comment]
disable windows defender or mark as safe i guess
